### ISSUE TITLE
Typo in di-ts-in-practice

### ISSUE THREAD

**Issue by dnischeta** [bespoyasov/www#16]
Hello, @bespoyasov .

I've found a typo in di-ts-in-practice post. Typo is marked bold in post fragment:

Вообще, понятие зависимостей зависит **то** контекста, но для простоты мы будем называть зависимостью любой модуль, который используется нашим. В тот момент, когда мы начинаем использовать любой модуль в других частях кода — он становится зависимостью.

P.S. Hope I didn't bother You with tiny typo, but issue creation seems the best action for me.

P.P.S. Thank you so much for Your projects (I'm reading your blog all day and also enjoying to get through solid interactive book).

**Comment by bespoyasov** [comment]
No bother at all! Thanks, fixed now :–)
Glad the blog is helpful ^_^
